# Generated by Django 3.0.7 on 2023-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='threedhtml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
