# Generated by Django 3.0.7 on 2023-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_threedhtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_markdown',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
